### ISSUE TITLE
MVP roadmap

### ISSUE THREAD

**Issue by Slashgear** [open-blog-initiative/open-blog.dev#4]
- [x] simple Vuepress custom color theme #11 
- [x] contributing.md #15 
- [x] Pull request template #22 
- [x] Explore page to list articles
- [x] Small readme to present the project @Slashgear #23 
- [x] Code of conduct #8 
- [x] License #7 
- [x] Author presentation component and data structure #10
